remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# General info
title: Executable Scenario Models
logo: /images/sesame_logo_tagline.svg
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

collections:
  agents:
    output: true
    relative_directory: agents
    permalink: /:collection/:path
  environments:
    output: true
    relative_directory: environments
    permalink: /:collection/:path
  oracles:
    output: true
    relative_directory: oracles
    permalink: /:collection/:path
  robots:
    output: true
    relative_directory: robots
    permalink: /:collection/:path
  runs:
    output: true
    relative_directory: runs
    permalink: /:collection/:path
  scenarios:
    output: true
    relative_directory: scenarios
    permalink: /:collection/:path
  tasks:
    output: true
    relative_directory: tasks/brsu_building_c_with_doors
    permalink: /:collection/:path

defaults:
  - scope:
      path: ""
    values:
      layout: default

url: https://hbrs-sesame.github.io
baseurl: /models